/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.JOptionPane;

/**
 *
 * @author Kyra Balliram
 */
public class BankingDetails extends javax.swing.JFrame {

    /**
     * Creates new form BankingDetails
     */
    public BankingDetails() {
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        JPaneBox = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        heading2lbl = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        monthlbl = new javax.swing.JLabel();
        yearlbl = new javax.swing.JLabel();
        cvvlbl = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cardNbrField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        addCardButton = new javax.swing.JButton();
        error1lbl = new javax.swing.JLabel();
        error7lbl = new javax.swing.JLabel();
        error3lbl = new javax.swing.JLabel();
        error4lbl = new javax.swing.JLabel();
        error5lbl = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        error2lbl = new javax.swing.JLabel();
        error6lbl = new javax.swing.JLabel();

        javax.swing.GroupLayout JPaneBoxLayout = new javax.swing.GroupLayout(JPaneBox.getContentPane());
        JPaneBox.getContentPane().setLayout(JPaneBoxLayout);
        JPaneBoxLayout.setHorizontalGroup(
            JPaneBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JPaneBoxLayout.setVerticalGroup(
            JPaneBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heading2lbl.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        heading2lbl.setForeground(new java.awt.Color(0, 153, 204));
        heading2lbl.setText("PAYPAL");
        jPanel3.add(heading2lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 12, 104, 26));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 227, 34));

        jLabel2.setText("Card Number (no spaces)");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, -1));

        monthlbl.setText("MM'");
        jPanel3.add(monthlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 34, -1));

        yearlbl.setText("YY'");
        jPanel3.add(yearlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 34, -1));

        cvvlbl.setText("CVV/CVWW");
        jPanel3.add(cvvlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 70, -1));
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 70, 40));

        jLabel1.setText("OTP pin");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 64, -1));

        cardNbrField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNbrFieldActionPerformed(evt);
            }
        });
        jPanel3.add(cardNbrField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 30));

        jLabel3.setText("Last Name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 64, -1));
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 227, 34));

        jLabel4.setText("First Name ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 64, -1));
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 227, 34));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, 40));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 50, 40));

        jRadioButton1.setText("male");
        jPanel3.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jCheckBox1.setText("female");
        jPanel3.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        addCardButton.setText("add card");
        addCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCardButtonActionPerformed(evt);
            }
        });
        jPanel3.add(addCardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 140, 20));
        jPanel3.add(error1lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 190, 30));
        jPanel3.add(error7lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 120, 30));
        jPanel3.add(error3lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 110, 30));
        jPanel3.add(error4lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 140, 30));
        jPanel3.add(error5lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 160, 30));

        jLabel22.setText("ID Number");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 64, -1));
        jPanel3.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 227, 34));
        jPanel3.add(error2lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 120, 30));
        jPanel3.add(error6lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 120, 30));

        jTabbedPane1.addTab("payment methods", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardNbrFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNbrFieldActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_cardNbrFieldActionPerformed

    private void addCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCardButtonActionPerformed
        // TODO add your handling code here:

        //checking card number: checking for length, if there is other digits and if it isd a mastercard?
        String currentCardNbr = cardNbrField.getText();
        int currentCardNbrLength = currentCardNbr.length();
        System.out.println(currentCardNbrLength);
        if (currentCardNbrLength == 16) {
            System.out.println("successfully added");
        } else if (currentCardNbrLength == 19) {
             error1lbl.setText("do not add sapces");
        } else if ( currentCardNbrLength>16){
            error1lbl.setText("card number length invalid");
        }


    }//GEN-LAST:event_addCardButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankingDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JPaneBox;
    private javax.swing.JButton addCardButton;
    private javax.swing.JTextField cardNbrField;
    private javax.swing.JLabel cvvlbl;
    private javax.swing.JLabel error1lbl;
    private javax.swing.JLabel error2lbl;
    private javax.swing.JLabel error3lbl;
    private javax.swing.JLabel error4lbl;
    private javax.swing.JLabel error5lbl;
    private javax.swing.JLabel error6lbl;
    private javax.swing.JLabel error7lbl;
    private javax.swing.JLabel heading2lbl;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel monthlbl;
    private javax.swing.JLabel yearlbl;
    // End of variables declaration//GEN-END:variables
}
